framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: 0.01
        #assets_version_format:  "stv%%2$s/%%1$s"
        #packages:
        #    css:
        #        version: 0.01
        #        version_format: "stv%%2$s/%%1$s"
        #    jsApp:
        #        version: 0.01
        #        version_format: "stv%%2$s/%%1$s"
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.pdo
        cookie_lifetime: 3600
        gc_maxlifetime: 7200
    fragments:       ~
    http_method_override: true