security:
    encoders:
        riki34\GameBundle\Entity\User: sha512

    providers:
        user_db:
            entity: { class: riki34\GameBundle\Entity\User }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /
                check_path: /login_check
            logout:
                path:   /logout
                target: /
