parameters:

services:
    game.JSONLoader:
        class: riki34\GameBundle\Service\JSONLoader

    game.RESTResponse:
        class: riki34\GameBundle\Service\RESTResponse

    game.locationLoader:
        class: riki34\GameBundle\Service\LocationLoader
        arguments: ["@doctrine.orm.default_entity_manager", "@game.JSONLoader", "@game.RESTResponse"]

    game.topic:
        class: riki34\GameBundle\Topic\GameTopic